export interface Estate {
      item_id: number,
      section_type: string,
      images_thumbnail: string,
      sales_type: string,
      sales_title: string,
      deposit: number,
      rent: number,
      size_m2: number,
      supply_area: {
        m2: number,
        p: string,
      },
      dedicate_area: {
        m2: number,
        p: string,
      },
      contract_area: {
        m2: number,
        p: string,
      },
      room_type_title: string,
      floor: string,
      floor_string: string,
      building_floor: string,
      title: string,
      is_first_movein: boolean,
      room_type: string,
      status: boolean,
      tags: Array<string>,
      service_type: string,
      random_location: {
        lat: number,
        lng: number,
      },
      manage_cost: string,
      reg_date: string,
      is_new: boolean,
      address_origin: {
        local1: string,
        local2: string,
        local3: string,
        local4: string,
        fullText: string,
        localText: string,
      },
      contract: string,
      address: string,
      is_zzim: boolean,
      address1: string,
      address2: string,
      address3: string,
      item_bm_type: string,
    }